### ISSUE TITLE
v.chi.sq 

### ISSUE THREAD

**Issue by maxgav13** [doomlab/MOTE#2]
Hi Erin

I was using your code and found a typo in the v.chi.sq function

Where it calculates 'v' it is 'sqrt(x2/n * dfsmall)' and I think it should be 'sqrt(x2/(n * dfsmall))'

Thanks for the code!! It helps a lot

**Comment by doomlab** [comment]
Hi @maxgav13 - don't know why I didn't get a notification about your issue but I have fixed that typo. Thanks for the heads up!
